### ISSUE TITLE
Feature Request: Support for Windows .zip files

### ISSUE THREAD

**Issue by ghost** [Gibberlings3/modhub#1]
I'd like to request a feature to support Windows packages in .zip format (in addition to .exe format). Creating a .exe format package is non-trivial on platforms other than Windows (i.e., requiring Wine).

I'd suggest creating a new tag, "wzp" for Windows .zip file. I think this would only require changing line 73 as follows:

$osregex = array("lin" => "/^lin/i", "osx" => "/^osx/i", "wzp" => "/^win.*zip$/i", "win" => "/exe$/i");

Windows zip files could be prefixed with "win" and have to be in .zip format. The regex suggested should avoid accidentally returning .exe files named win-[MODNAME].exe.

**Comment by lynxlynxlynx** [comment]
Sure, like you said, it's trivial. The packaging stuff was added for the g3 way of doing things, but there's no reason not to extend it. Do you already have a mod somewhere I could test against?

**Comment by ghost** [comment]
Cool! Thanks!

**Comment by ghost** [comment]
Re: testing

I have updated the naming format of some of my mods. The filenames had been in [MODNAME]-[VER]-[OS] order, but I've renamed the packages to comply with G3's [OS]-[MODNAME]-[VER] convention.

You can test with:
https://github.com/AstroBryGuy/NeeraBanters (no linux package)
https://github.com/AstroBryGuy/ChattyImoen
https://github.com/AstroBryGuy/JaheiraRecast

Thanks!
AstroBryGuy

**Comment by lynxlynxlynx** [comment]
Done and deployed.
