### ISSUE TITLE
Support for the package prefix `mac-` as a synonym of `osx-`

### ISSUE THREAD

**Issue by skellytz** [Gibberlings3/modhub#12]
Would it be possible for `osx-` to also catch `mac-`prefixed packages (make them synonyms) to allow modders to use more up-to-date package naming?

**Comment by lynxlynxlynx** [comment]
Can you give me a test case?

**Comment by skellytz** [comment]
https://github.com/Argent77/DjinniCompanion

[Weidu Mod Packager](https://github.com/InfinityTools/WeiduModPackager) currently defaults to `osx-` but can also generate `mac-` if preferred.

It would be best if we didn't have to update modhub links that are already with, e.g. `pkg=osx,zip` to `pkg=osx,mac,zip` when a mod maintainer decides to change the prefix; I suggest making them synonyms rather than separate prefixes.

**Comment by skellytz** [comment]
Awesome! Thanks! 🎉
